import { App } from "../app";
export class Preloader {
  imglist: string[] = [
    require("../assets/airdefence.png"),
    require("../assets/base.png"),
    require("../assets/electricityfactory.png"),
    require("../assets/lost.jpg"),
    require("../assets/map.png"),
    require("../assets/powervalue.png"),
    require("../assets/solderfactory.png"),
    require("../assets/victory.jpg"),
    require("../assets/warcarfactory.png"),
    require("../assets/baseimgs/base1.png"),
    require("../assets/baseimgs/base10.png"),
    require("../assets/baseimgs/base11.png"),
    require("../assets/baseimgs/base12.png"),
    require("../assets/baseimgs/base13.png"),
    require("../assets/baseimgs/base14.png"),
    require("../assets/baseimgs/base2.png"),
    require("../assets/baseimgs/base3.png"),
    require("../assets/baseimgs/base4.png"),
    require("../assets/baseimgs/base5.png"),
    require("../assets/baseimgs/base6.png"),
    require("../assets/baseimgs/base7.png"),
    require("../assets/baseimgs/base8.png"),
    require("../assets/baseimgs/base9.png"),
    require("../assets/buildings-structure/gd_prismtower.png"),
    require("../assets/buildings-structure/soilder_engineer.png"),
    require("../assets/buildings-structure/soilder_liberationarmy.png"),
    require("../assets/buildings-structure/soilder_spy.png"),
    require("../assets/buildings-structure/st_infantry.png"),
    require("../assets/buildings-structure/st_oil.png"),
    require("../assets/buildings-structure/st_powerstation.png"),
    require("../assets/buildings-structure/tk_rhinocerotidae.png"),
    require("../assets/buildings-structure/tk_skystart.png"),
    require("../assets/buildings-structure/wcf.png"),
    require("../assets/covers/covers (1).jpg"),
    require("../assets/covers/covers (10).jpg"),
    require("../assets/covers/covers (11).jpg"),
    require("../assets/covers/covers (12).jpg"),
    require("../assets/covers/covers (13).jpg"),
    require("../assets/covers/covers (14).jpg"),
    require("../assets/covers/covers (15).jpg"),
    require("../assets/covers/covers (16).jpg"),
    require("../assets/covers/covers (17).jpg"),
    require("../assets/covers/covers (18).jpg"),
    require("../assets/covers/covers (19).jpg"),
    require("../assets/covers/covers (2).jpg"),
    require("../assets/covers/covers (20).jpg"),
    require("../assets/covers/covers (21).jpg"),
    require("../assets/covers/covers (22).jpg"),
    require("../assets/covers/covers (23).jpg"),
    require("../assets/covers/covers (24).jpg"),
    require("../assets/covers/covers (25).jpg"),
    require("../assets/covers/covers (26).jpg"),
    require("../assets/covers/covers (27).jpg"),
    require("../assets/covers/covers (28).jpg"),
    require("../assets/covers/covers (29).jpg"),
    require("../assets/covers/covers (3).jpg"),
    require("../assets/covers/covers (30).jpg"),
    require("../assets/covers/covers (31).jpg"),
    require("../assets/covers/covers (4).jpg"),
    require("../assets/covers/covers (5).jpg"),
    require("../assets/covers/covers (6).jpg"),
    require("../assets/covers/covers (7).jpg"),
    require("../assets/covers/covers (8).jpg"),
    require("../assets/covers/covers (9).jpg"),
    require("../assets/covers/cover_left.jpg"),
    require("../assets/covers/cover_right.jpg"),
    require("../assets/covers/E4U$]XAXA8V(25HP4PW~62O.png"),
    require("../assets/covers/right_boardtop.jpg"),
    require("../assets/covers/selection_items.jpg"),
    require("../assets/covers/Y2$W%F1L76IZZ{FULVP1Y[4.jpg"),
    require("../assets/engineer/eng_b1.png"),
    require("../assets/engineer/eng_b2.png"),
    require("../assets/engineer/eng_b3.png"),
    require("../assets/engineer/eng_b4.png"),
    require("../assets/engineer/eng_b5.png"),
    require("../assets/engineer/eng_l1.png"),
    require("../assets/engineer/eng_l2.png"),
    require("../assets/engineer/eng_l3.png"),
    require("../assets/engineer/eng_l4.png"),
    require("../assets/engineer/eng_l5.png"),
    require("../assets/engineer/eng_lb1.png"),
    require("../assets/engineer/eng_lb2.png"),
    require("../assets/engineer/eng_lb3.png"),
    require("../assets/engineer/eng_lb4.png"),
    require("../assets/engineer/eng_lb5.png"),
    require("../assets/engineer/eng_lt1.png"),
    require("../assets/engineer/eng_lt2.png"),
    require("../assets/engineer/eng_lt3.png"),
    require("../assets/engineer/eng_lt4.png"),
    require("../assets/engineer/eng_lt5.png"),
    require("../assets/engineer/eng_r1.png"),
    require("../assets/engineer/eng_r2.png"),
    require("../assets/engineer/eng_r3.png"),
    require("../assets/engineer/eng_r4.png"),
    require("../assets/engineer/eng_r5.png"),
    require("../assets/engineer/eng_rb1.png"),
    require("../assets/engineer/eng_rb2.png"),
    require("../assets/engineer/eng_rb3.png"),
    require("../assets/engineer/eng_rb4.png"),
    require("../assets/engineer/eng_rb5.png"),
    require("../assets/engineer/eng_rt1.png"),
    require("../assets/engineer/eng_rt2.png"),
    require("../assets/engineer/eng_rt3.png"),
    require("../assets/engineer/eng_rt4.png"),
    require("../assets/engineer/eng_rt5.png"),
    require("../assets/engineer/eng_t1.png"),
    require("../assets/engineer/eng_t2.png"),
    require("../assets/engineer/eng_t3.png"),
    require("../assets/engineer/eng_t4.png"),
    require("../assets/engineer/eng_t5.png"),
    require("../assets/infantry/infantry-1.png"),
    require("../assets/infantry/infantry-2.png"),
    require("../assets/infantry/infantry-3.png"),
    require("../assets/infantry/infantry-4.png"),
    require("../assets/infantry/infantry-5.png"),
    require("../assets/infantry/infantry-6.png"),
    require("../assets/oilstructure/oil1.png"),
    require("../assets/oilstructure/oil2.png"),
    require("../assets/oilstructure/oil3.png"),
    require("../assets/oilstructure/oil4.png"),
    require("../assets/oilstructure/oil5.png"),
    require("../assets/oilstructure/oil6.png"),
    require("../assets/oilstructure/oil7.png"),
    require("../assets/powerstation/p-b1.png"),
    require("../assets/powerstation/p-b2.png"),
    require("../assets/powerstation/p-b3.png"),
    require("../assets/powerstation/p-b4.png"),
    require("../assets/powerstation/p-b5.png"),
    require("../assets/powerstation/p-b6.png"),
    require("../assets/powerstation/p-s1.png"),
    require("../assets/powerstation/p-s2.png"),
    require("../assets/powerstation/p-s3.png"),
    require("../assets/powerstation/p-s4.png"),
    require("../assets/powerstation/p-s5.png"),
    require("../assets/powerstation/p-s6.png"),
    require("../assets/prismtower/pt_b1.png"),
    require("../assets/prismtower/pt_b2.png"),
    require("../assets/prismtower/pt_b3.png"),
    require("../assets/prismtower/pt_b4.png"),
    require("../assets/prismtower/pt_b5.png"),
    require("../assets/prismtower/pt_b6.png"),
    require("../assets/prismtower/pt_s1.png"),
    require("../assets/prismtower/pt_s2.png"),
    require("../assets/prismtower/pt_s3.png"),
    require("../assets/prismtower/pt_s4.png"),
    require("../assets/prismtower/pt_s5.png"),
    require("../assets/prismtower/pt_s6.png"),
    require("../assets/prismtower/pt_s7.png"),
    require("../assets/prismtower/pt_s8.png"),
    require("../assets/prismtower/pt_s9.png"),
    require("../assets/rhinocerotidaetank/rhi_b.png"),
    require("../assets/rhinocerotidaetank/rhi_l.png"),
    require("../assets/rhinocerotidaetank/rhi_lb.png"),
    require("../assets/rhinocerotidaetank/rhi_lt.png"),
    require("../assets/rhinocerotidaetank/rhi_r.png"),
    require("../assets/rhinocerotidaetank/rhi_rb.png"),
    require("../assets/rhinocerotidaetank/rhi_rt.png"),
    require("../assets/rhinocerotidaetank/rhi_t.png"),
    require("../assets/rightbar/s1.png"),
    require("../assets/rightbar/s2.png"),
    require("../assets/rightbar/s3.png"),
    require("../assets/rightbar/s4.png"),
    require("../assets/rightbar/us1.png"),
    require("../assets/rightbar/us2.png"),
    require("../assets/rightbar/us3.png"),
    require("../assets/rightbar/us4.png"),
    require("../assets/skytank/sky_b.png"),
    require("../assets/skytank/sky_l.png"),
    require("../assets/skytank/sky_lb.png"),
    require("../assets/skytank/sky_lt.png"),
    require("../assets/skytank/sky_r.png"),
    require("../assets/skytank/sky_rb.png"),
    require("../assets/skytank/sky_rt.png"),
    require("../assets/skytank/sky_t.png"),
    require("../assets/soilderimgs/b1.png"),
    require("../assets/soilderimgs/b2.png"),
    require("../assets/soilderimgs/b3.png"),
    require("../assets/soilderimgs/b4.png"),
    require("../assets/soilderimgs/b5.png"),
    require("../assets/soilderimgs/l1.png"),
    require("../assets/soilderimgs/l2.png"),
    require("../assets/soilderimgs/l3.png"),
    require("../assets/soilderimgs/l4.png"),
    require("../assets/soilderimgs/l5.png"),
    require("../assets/soilderimgs/lb1.png"),
    require("../assets/soilderimgs/lb2.png"),
    require("../assets/soilderimgs/lb3.png"),
    require("../assets/soilderimgs/lb4.png"),
    require("../assets/soilderimgs/lb5.png"),
    require("../assets/soilderimgs/lt1.png"),
    require("../assets/soilderimgs/lt2.png"),
    require("../assets/soilderimgs/lt3.png"),
    require("../assets/soilderimgs/lt4.png"),
    require("../assets/soilderimgs/lt5.png"),
    require("../assets/soilderimgs/r1.png"),
    require("../assets/soilderimgs/r2.png"),
    require("../assets/soilderimgs/r3.png"),
    require("../assets/soilderimgs/r4.png"),
    require("../assets/soilderimgs/r5.png"),
    require("../assets/soilderimgs/rb1.png"),
    require("../assets/soilderimgs/rb2.png"),
    require("../assets/soilderimgs/rb3.png"),
    require("../assets/soilderimgs/rb4.png"),
    require("../assets/soilderimgs/rb5.png"),
    require("../assets/soilderimgs/rt1.png"),
    require("../assets/soilderimgs/rt2.png"),
    require("../assets/soilderimgs/rt3.png"),
    require("../assets/soilderimgs/rt4.png"),
    require("../assets/soilderimgs/rt5.png"),
    require("../assets/soilderimgs/t1.png"),
    require("../assets/soilderimgs/t2.png"),
    require("../assets/soilderimgs/t3.png"),
    require("../assets/soilderimgs/t4.png"),
    require("../assets/soilderimgs/t5.png"),
    require("../assets/wcf/wcf1.png"),
    require("../assets/wcf/wcf2.png"),
    require("../assets/wcf/wcf3.png"),
    require("../assets/wcf/wcf4.png"),
    require("../assets/wcf/wcf5.png"),
    require("../assets/baseimgs/enemy_base/base1.png"),
    require("../assets/baseimgs/enemy_base/base10.png"),
    require("../assets/baseimgs/enemy_base/base11.png"),
    require("../assets/baseimgs/enemy_base/base12.png"),
    require("../assets/baseimgs/enemy_base/base13.png"),
    require("../assets/baseimgs/enemy_base/base14.png"),
    require("../assets/baseimgs/enemy_base/base2.png"),
    require("../assets/baseimgs/enemy_base/base3.png"),
    require("../assets/baseimgs/enemy_base/base4.png"),
    require("../assets/baseimgs/enemy_base/base5.png"),
    require("../assets/baseimgs/enemy_base/base6.png"),
    require("../assets/baseimgs/enemy_base/base7.png"),
    require("../assets/baseimgs/enemy_base/base8.png"),
    require("../assets/baseimgs/enemy_base/base9.png"),
    require("../assets/covers/dic1/covers (1).jpg"),
    require("../assets/covers/dic1/covers (10).jpg"),
    require("../assets/covers/dic1/covers (11).jpg"),
    require("../assets/covers/dic1/covers (12).jpg"),
    require("../assets/covers/dic1/covers (13).jpg"),
    require("../assets/covers/dic1/covers (14).jpg"),
    require("../assets/covers/dic1/covers (15).jpg"),
    require("../assets/covers/dic1/covers (16).jpg"),
    require("../assets/covers/dic1/covers (17).jpg"),
    require("../assets/covers/dic1/covers (18).jpg"),
    require("../assets/covers/dic1/covers (19).jpg"),
    require("../assets/covers/dic1/covers (2).jpg"),
    require("../assets/covers/dic1/covers (20).jpg"),
    require("../assets/covers/dic1/covers (21).jpg"),
    require("../assets/covers/dic1/covers (22).jpg"),
    require("../assets/covers/dic1/covers (23).jpg"),
    require("../assets/covers/dic1/covers (24).jpg"),
    require("../assets/covers/dic1/covers (25).jpg"),
    require("../assets/covers/dic1/covers (26).jpg"),
    require("../assets/covers/dic1/covers (27).jpg"),
    require("../assets/covers/dic1/covers (28).jpg"),
    require("../assets/covers/dic1/covers (29).jpg"),
    require("../assets/covers/dic1/covers (3).jpg"),
    require("../assets/covers/dic1/covers (30).jpg"),
    require("../assets/covers/dic1/covers (31).jpg"),
    require("../assets/covers/dic1/covers (4).jpg"),
    require("../assets/covers/dic1/covers (5).jpg"),
    require("../assets/covers/dic1/covers (6).jpg"),
    require("../assets/covers/dic1/covers (7).jpg"),
    require("../assets/covers/dic1/covers (8).jpg"),
    require("../assets/covers/dic1/covers (9).jpg"),
    require("../assets/enemy/baseimgs/enemy_base1.png"),
    require("../assets/enemy/baseimgs/enemy_base10.png"),
    require("../assets/enemy/baseimgs/enemy_base11.png"),
    require("../assets/enemy/baseimgs/enemy_base12.png"),
    require("../assets/enemy/baseimgs/enemy_base13.png"),
    require("../assets/enemy/baseimgs/enemy_base14.png"),
    require("../assets/enemy/baseimgs/enemy_base2.png"),
    require("../assets/enemy/baseimgs/enemy_base3.png"),
    require("../assets/enemy/baseimgs/enemy_base4.png"),
    require("../assets/enemy/baseimgs/enemy_base5.png"),
    require("../assets/enemy/baseimgs/enemy_base6.png"),
    require("../assets/enemy/baseimgs/enemy_base7.png"),
    require("../assets/enemy/baseimgs/enemy_base8.png"),
    require("../assets/enemy/baseimgs/enemy_base9.png"),
    require("../assets/enemy/engineer/enemy_eng_b1.png"),
    require("../assets/enemy/engineer/enemy_eng_b2.png"),
    require("../assets/enemy/engineer/enemy_eng_b3.png"),
    require("../assets/enemy/engineer/enemy_eng_b4.png"),
    require("../assets/enemy/engineer/enemy_eng_b5.png"),
    require("../assets/enemy/engineer/enemy_eng_l1.png"),
    require("../assets/enemy/engineer/enemy_eng_l2.png"),
    require("../assets/enemy/engineer/enemy_eng_l3.png"),
    require("../assets/enemy/engineer/enemy_eng_l4.png"),
    require("../assets/enemy/engineer/enemy_eng_l5.png"),
    require("../assets/enemy/engineer/enemy_eng_lb1.png"),
    require("../assets/enemy/engineer/enemy_eng_lb2.png"),
    require("../assets/enemy/engineer/enemy_eng_lb3.png"),
    require("../assets/enemy/engineer/enemy_eng_lb4.png"),
    require("../assets/enemy/engineer/enemy_eng_lb5.png"),
    require("../assets/enemy/engineer/enemy_eng_lt1.png"),
    require("../assets/enemy/engineer/enemy_eng_lt2.png"),
    require("../assets/enemy/engineer/enemy_eng_lt3.png"),
    require("../assets/enemy/engineer/enemy_eng_lt4.png"),
    require("../assets/enemy/engineer/enemy_eng_lt5.png"),
    require("../assets/enemy/engineer/enemy_eng_r1.png"),
    require("../assets/enemy/engineer/enemy_eng_r2.png"),
    require("../assets/enemy/engineer/enemy_eng_r3.png"),
    require("../assets/enemy/engineer/enemy_eng_r4.png"),
    require("../assets/enemy/engineer/enemy_eng_r5.png"),
    require("../assets/enemy/engineer/enemy_eng_rb1.png"),
    require("../assets/enemy/engineer/enemy_eng_rb2.png"),
    require("../assets/enemy/engineer/enemy_eng_rb3.png"),
    require("../assets/enemy/engineer/enemy_eng_rb4.png"),
    require("../assets/enemy/engineer/enemy_eng_rb5.png"),
    require("../assets/enemy/engineer/enemy_eng_rt1.png"),
    require("../assets/enemy/engineer/enemy_eng_rt2.png"),
    require("../assets/enemy/engineer/enemy_eng_rt3.png"),
    require("../assets/enemy/engineer/enemy_eng_rt4.png"),
    require("../assets/enemy/engineer/enemy_eng_rt5.png"),
    require("../assets/enemy/engineer/enemy_eng_t1.png"),
    require("../assets/enemy/engineer/enemy_eng_t2.png"),
    require("../assets/enemy/engineer/enemy_eng_t3.png"),
    require("../assets/enemy/engineer/enemy_eng_t4.png"),
    require("../assets/enemy/engineer/enemy_eng_t5.png"),
    require("../assets/enemy/infantry/enemy_infantry-1.png"),
    require("../assets/enemy/infantry/enemy_infantry-2.png"),
    require("../assets/enemy/infantry/enemy_infantry-3.png"),
    require("../assets/enemy/infantry/enemy_infantry-4.png"),
    require("../assets/enemy/infantry/enemy_infantry-5.png"),
    require("../assets/enemy/infantry/enemy_infantry-6.png"),
    require("../assets/enemy/oilstructure/enemy_oil1.png"),
    require("../assets/enemy/oilstructure/enemy_oil2.png"),
    require("../assets/enemy/oilstructure/enemy_oil3.png"),
    require("../assets/enemy/oilstructure/enemy_oil4.png"),
    require("../assets/enemy/oilstructure/enemy_oil5.png"),
    require("../assets/enemy/oilstructure/enemy_oil6.png"),
    require("../assets/enemy/oilstructure/enemy_oil7.png"),
    require("../assets/enemy/powerstation/enemy_p-b1.png"),
    require("../assets/enemy/powerstation/enemy_p-b2.png"),
    require("../assets/enemy/powerstation/enemy_p-b3.png"),
    require("../assets/enemy/powerstation/enemy_p-b4.png"),
    require("../assets/enemy/powerstation/enemy_p-b5.png"),
    require("../assets/enemy/powerstation/enemy_p-b6.png"),
    require("../assets/enemy/powerstation/enemy_p-s1.png"),
    require("../assets/enemy/powerstation/enemy_p-s2.png"),
    require("../assets/enemy/powerstation/enemy_p-s3.png"),
    require("../assets/enemy/powerstation/enemy_p-s4.png"),
    require("../assets/enemy/powerstation/enemy_p-s5.png"),
    require("../assets/enemy/powerstation/enemy_p-s6.png"),
    require("../assets/enemy/prismtower/enemy_pt_b1.png"),
    require("../assets/enemy/prismtower/enemy_pt_b2.png"),
    require("../assets/enemy/prismtower/enemy_pt_b3.png"),
    require("../assets/enemy/prismtower/enemy_pt_b4.png"),
    require("../assets/enemy/prismtower/enemy_pt_b5.png"),
    require("../assets/enemy/prismtower/enemy_pt_b6.png"),
    require("../assets/enemy/prismtower/enemy_pt_s1.png"),
    require("../assets/enemy/prismtower/enemy_pt_s2.png"),
    require("../assets/enemy/prismtower/enemy_pt_s3.png"),
    require("../assets/enemy/prismtower/enemy_pt_s4.png"),
    require("../assets/enemy/prismtower/enemy_pt_s5.png"),
    require("../assets/enemy/prismtower/enemy_pt_s6.png"),
    require("../assets/enemy/prismtower/enemy_pt_s7.png"),
    require("../assets/enemy/prismtower/enemy_pt_s8.png"),
    require("../assets/enemy/prismtower/enemy_pt_s9.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_b.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_l.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_lb.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_lt.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_r.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_rb.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_rt.png"),
    require("../assets/enemy/rhinocerotidaetank/enemy_rhi_t.png"),
    require("../assets/enemy/rightbar/s1.png"),
    require("../assets/enemy/rightbar/s2.png"),
    require("../assets/enemy/rightbar/s3.png"),
    require("../assets/enemy/rightbar/s4.png"),
    require("../assets/enemy/rightbar/us1.png"),
    require("../assets/enemy/rightbar/us2.png"),
    require("../assets/enemy/rightbar/us3.png"),
    require("../assets/enemy/rightbar/us4.png"),
    require("../assets/enemy/skytank/enemy_sky_b.png"),
    require("../assets/enemy/skytank/enemy_sky_l.png"),
    require("../assets/enemy/skytank/enemy_sky_lb.png"),
    require("../assets/enemy/skytank/enemy_sky_lt.png"),
    require("../assets/enemy/skytank/enemy_sky_r.png"),
    require("../assets/enemy/skytank/enemy_sky_rb.png"),
    require("../assets/enemy/skytank/enemy_sky_rt.png"),
    require("../assets/enemy/skytank/enemy_sky_t.png"),
    require("../assets/enemy/soilderimgs/enemy_b1.png"),
    require("../assets/enemy/soilderimgs/enemy_b2.png"),
    require("../assets/enemy/soilderimgs/enemy_b3.png"),
    require("../assets/enemy/soilderimgs/enemy_b4.png"),
    require("../assets/enemy/soilderimgs/enemy_b5.png"),
    require("../assets/enemy/soilderimgs/enemy_l1.png"),
    require("../assets/enemy/soilderimgs/enemy_l2.png"),
    require("../assets/enemy/soilderimgs/enemy_l3.png"),
    require("../assets/enemy/soilderimgs/enemy_l4.png"),
    require("../assets/enemy/soilderimgs/enemy_l5.png"),
    require("../assets/enemy/soilderimgs/enemy_lb1.png"),
    require("../assets/enemy/soilderimgs/enemy_lb2.png"),
    require("../assets/enemy/soilderimgs/enemy_lb3.png"),
    require("../assets/enemy/soilderimgs/enemy_lb4.png"),
    require("../assets/enemy/soilderimgs/enemy_lb5.png"),
    require("../assets/enemy/soilderimgs/enemy_lt1.png"),
    require("../assets/enemy/soilderimgs/enemy_lt2.png"),
    require("../assets/enemy/soilderimgs/enemy_lt3.png"),
    require("../assets/enemy/soilderimgs/enemy_lt4.png"),
    require("../assets/enemy/soilderimgs/enemy_lt5.png"),
    require("../assets/enemy/soilderimgs/enemy_r1.png"),
    require("../assets/enemy/soilderimgs/enemy_r2.png"),
    require("../assets/enemy/soilderimgs/enemy_r3.png"),
    require("../assets/enemy/soilderimgs/enemy_r4.png"),
    require("../assets/enemy/soilderimgs/enemy_r5.png"),
    require("../assets/enemy/soilderimgs/enemy_rb1.png"),
    require("../assets/enemy/soilderimgs/enemy_rb2.png"),
    require("../assets/enemy/soilderimgs/enemy_rb3.png"),
    require("../assets/enemy/soilderimgs/enemy_rb4.png"),
    require("../assets/enemy/soilderimgs/enemy_rb5.png"),
    require("../assets/enemy/soilderimgs/enemy_rt1.png"),
    require("../assets/enemy/soilderimgs/enemy_rt2.png"),
    require("../assets/enemy/soilderimgs/enemy_rt3.png"),
    require("../assets/enemy/soilderimgs/enemy_rt4.png"),
    require("../assets/enemy/soilderimgs/enemy_rt5.png"),
    require("../assets/enemy/soilderimgs/enemy_t1.png"),
    require("../assets/enemy/soilderimgs/enemy_t2.png"),
    require("../assets/enemy/soilderimgs/enemy_t3.png"),
    require("../assets/enemy/soilderimgs/enemy_t4.png"),
    require("../assets/enemy/soilderimgs/enemy_t5.png"),
    require("../assets/enemy/wcf/enemy_wcf1.png"),
    require("../assets/enemy/wcf/enemy_wcf2.png"),
    require("../assets/enemy/wcf/enemy_wcf3.png"),
    require("../assets/enemy/wcf/enemy_wcf4.png"),
    require("../assets/enemy/wcf/enemy_wcf5.png"),
    require("../assets/engineer/enemy_eng/eng_b1.png"),
    require("../assets/engineer/enemy_eng/eng_b2.png"),
    require("../assets/engineer/enemy_eng/eng_b3.png"),
    require("../assets/engineer/enemy_eng/eng_b4.png"),
    require("../assets/engineer/enemy_eng/eng_b5.png"),
    require("../assets/engineer/enemy_eng/eng_l1.png"),
    require("../assets/engineer/enemy_eng/eng_l2.png"),
    require("../assets/engineer/enemy_eng/eng_l3.png"),
    require("../assets/engineer/enemy_eng/eng_l4.png"),
    require("../assets/engineer/enemy_eng/eng_l5.png"),
    require("../assets/engineer/enemy_eng/eng_lb1.png"),
    require("../assets/engineer/enemy_eng/eng_lb2.png"),
    require("../assets/engineer/enemy_eng/eng_lb3.png"),
    require("../assets/engineer/enemy_eng/eng_lb4.png"),
    require("../assets/engineer/enemy_eng/eng_lb5.png"),
    require("../assets/engineer/enemy_eng/eng_lt1.png"),
    require("../assets/engineer/enemy_eng/eng_lt2.png"),
    require("../assets/engineer/enemy_eng/eng_lt3.png"),
    require("../assets/engineer/enemy_eng/eng_lt4.png"),
    require("../assets/engineer/enemy_eng/eng_lt5.png"),
    require("../assets/engineer/enemy_eng/eng_r1.png"),
    require("../assets/engineer/enemy_eng/eng_r2.png"),
    require("../assets/engineer/enemy_eng/eng_r3.png"),
    require("../assets/engineer/enemy_eng/eng_r4.png"),
    require("../assets/engineer/enemy_eng/eng_r5.png"),
    require("../assets/engineer/enemy_eng/eng_rb1.png"),
    require("../assets/engineer/enemy_eng/eng_rb2.png"),
    require("../assets/engineer/enemy_eng/eng_rb3.png"),
    require("../assets/engineer/enemy_eng/eng_rb4.png"),
    require("../assets/engineer/enemy_eng/eng_rb5.png"),
    require("../assets/engineer/enemy_eng/eng_rt1.png"),
    require("../assets/engineer/enemy_eng/eng_rt2.png"),
    require("../assets/engineer/enemy_eng/eng_rt3.png"),
    require("../assets/engineer/enemy_eng/eng_rt4.png"),
    require("../assets/engineer/enemy_eng/eng_rt5.png"),
    require("../assets/engineer/enemy_eng/eng_t1.png"),
    require("../assets/engineer/enemy_eng/eng_t2.png"),
    require("../assets/engineer/enemy_eng/eng_t3.png"),
    require("../assets/engineer/enemy_eng/eng_t4.png"),
    require("../assets/engineer/enemy_eng/eng_t5.png"),
    require("../assets/infantry/enemy_infantry/infantry-1.png"),
    require("../assets/infantry/enemy_infantry/infantry-2.png"),
    require("../assets/infantry/enemy_infantry/infantry-3.png"),
    require("../assets/infantry/enemy_infantry/infantry-4.png"),
    require("../assets/infantry/enemy_infantry/infantry-5.png"),
    require("../assets/infantry/enemy_infantry/infantry-6.png"),
    require("../assets/oilstructure/enemy_oil/oil1.png"),
    require("../assets/oilstructure/enemy_oil/oil2.png"),
    require("../assets/oilstructure/enemy_oil/oil3.png"),
    require("../assets/oilstructure/enemy_oil/oil4.png"),
    require("../assets/oilstructure/enemy_oil/oil5.png"),
    require("../assets/oilstructure/enemy_oil/oil6.png"),
    require("../assets/oilstructure/enemy_oil/oil7.png"),
    require("../assets/powerstation/enemy_pb/p-b1.png"),
    require("../assets/powerstation/enemy_pb/p-b2.png"),
    require("../assets/powerstation/enemy_pb/p-b3.png"),
    require("../assets/powerstation/enemy_pb/p-b4.png"),
    require("../assets/powerstation/enemy_pb/p-b5.png"),
    require("../assets/powerstation/enemy_pb/p-b6.png"),
    require("../assets/powerstation/enemy_pb/p-s1.png"),
    require("../assets/powerstation/enemy_pb/p-s2.png"),
    require("../assets/powerstation/enemy_pb/p-s3.png"),
    require("../assets/powerstation/enemy_pb/p-s4.png"),
    require("../assets/powerstation/enemy_pb/p-s5.png"),
    require("../assets/powerstation/enemy_pb/p-s6.png"),
    require("../assets/prismtower/enemy_pt/pt_b1.png"),
    require("../assets/prismtower/enemy_pt/pt_b2.png"),
    require("../assets/prismtower/enemy_pt/pt_b3.png"),
    require("../assets/prismtower/enemy_pt/pt_b4.png"),
    require("../assets/prismtower/enemy_pt/pt_b5.png"),
    require("../assets/prismtower/enemy_pt/pt_b6.png"),
    require("../assets/prismtower/enemy_pt/pt_s1.png"),
    require("../assets/prismtower/enemy_pt/pt_s2.png"),
    require("../assets/prismtower/enemy_pt/pt_s3.png"),
    require("../assets/prismtower/enemy_pt/pt_s4.png"),
    require("../assets/prismtower/enemy_pt/pt_s5.png"),
    require("../assets/prismtower/enemy_pt/pt_s6.png"),
    require("../assets/prismtower/enemy_pt/pt_s7.png"),
    require("../assets/prismtower/enemy_pt/pt_s8.png"),
    require("../assets/prismtower/enemy_pt/pt_s9.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetank-lb.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetankbot.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetanklef.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetanklt.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetankrb.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetankrig.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetankrt.png"),
    require("../assets/rhinocerotidaetank/enemy_rhi/rhinocerotidaetanktop.png"),
    require("../assets/rhinocerotidaetank/expolision/expolision_1.png"),
    require("../assets/rhinocerotidaetank/expolision/expolision_2.png"),
    require("../assets/rhinocerotidaetank/expolision/expolision_3.png"),
    require("../assets/rhinocerotidaetank/expolision/expolision_4.png"),
    require("../assets/rhinocerotidaetank/expolision/expolision_5.png"),
    require("../assets/rhinocerotidaetank/expolision/expolision_6.png"),
    require("../assets/rhinocerotidaetank/expolision/expolision_7.png"),
    require("../assets/skytank/enemy_sky/sky_b.png"),
    require("../assets/skytank/enemy_sky/sky_l.png"),
    require("../assets/skytank/enemy_sky/sky_lb.png"),
    require("../assets/skytank/enemy_sky/sky_lt.png"),
    require("../assets/skytank/enemy_sky/sky_r.png"),
    require("../assets/skytank/enemy_sky/sky_rb.png"),
    require("../assets/skytank/enemy_sky/sky_rt.png"),
    require("../assets/skytank/enemy_sky/sky_t.png"),
    require("../assets/soilderimgs/enemy_soilder/b1.png"),
    require("../assets/soilderimgs/enemy_soilder/b2.png"),
    require("../assets/soilderimgs/enemy_soilder/b3.png"),
    require("../assets/soilderimgs/enemy_soilder/b4.png"),
    require("../assets/soilderimgs/enemy_soilder/b5.png"),
    require("../assets/soilderimgs/enemy_soilder/l1.png"),
    require("../assets/soilderimgs/enemy_soilder/l2.png"),
    require("../assets/soilderimgs/enemy_soilder/l3.png"),
    require("../assets/soilderimgs/enemy_soilder/l4.png"),
    require("../assets/soilderimgs/enemy_soilder/l5.png"),
    require("../assets/soilderimgs/enemy_soilder/lb1.png"),
    require("../assets/soilderimgs/enemy_soilder/lb2.png"),
    require("../assets/soilderimgs/enemy_soilder/lb3.png"),
    require("../assets/soilderimgs/enemy_soilder/lb4.png"),
    require("../assets/soilderimgs/enemy_soilder/lb5.png"),
    require("../assets/soilderimgs/enemy_soilder/lt1.png"),
    require("../assets/soilderimgs/enemy_soilder/lt2.png"),
    require("../assets/soilderimgs/enemy_soilder/lt3.png"),
    require("../assets/soilderimgs/enemy_soilder/lt4.png"),
    require("../assets/soilderimgs/enemy_soilder/lt5.png"),
    require("../assets/soilderimgs/enemy_soilder/r1.png"),
    require("../assets/soilderimgs/enemy_soilder/r2.png"),
    require("../assets/soilderimgs/enemy_soilder/r3.png"),
    require("../assets/soilderimgs/enemy_soilder/r4.png"),
    require("../assets/soilderimgs/enemy_soilder/r5.png"),
    require("../assets/soilderimgs/enemy_soilder/rb1.png"),
    require("../assets/soilderimgs/enemy_soilder/rb2.png"),
    require("../assets/soilderimgs/enemy_soilder/rb3.png"),
    require("../assets/soilderimgs/enemy_soilder/rb4.png"),
    require("../assets/soilderimgs/enemy_soilder/rb5.png"),
    require("../assets/soilderimgs/enemy_soilder/rt1.png"),
    require("../assets/soilderimgs/enemy_soilder/rt2.png"),
    require("../assets/soilderimgs/enemy_soilder/rt3.png"),
    require("../assets/soilderimgs/enemy_soilder/rt4.png"),
    require("../assets/soilderimgs/enemy_soilder/rt5.png"),
    require("../assets/soilderimgs/enemy_soilder/t1.png"),
    require("../assets/soilderimgs/enemy_soilder/t2.png"),
    require("../assets/soilderimgs/enemy_soilder/t3.png"),
    require("../assets/soilderimgs/enemy_soilder/t4.png"),
    require("../assets/soilderimgs/enemy_soilder/t5.png"),
    require("../assets/soilderimgs/soilder_attack_img/fire_flash.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_b.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_l.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_lb.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_lt.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_r.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_rb.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_rt.png"),
    require("../assets/soilderimgs/soilder_attack_img/s_t.png"),
    require("../assets/wcf/enemy_wcf/wcf1.png"),
    require("../assets/wcf/enemy_wcf/wcf2.png"),
    require("../assets/wcf/enemy_wcf/wcf3.png"),
    require("../assets/wcf/enemy_wcf/wcf4.png"),
    require("../assets/wcf/enemy_wcf/wcf5.png"),
  ];
  progress: Number = 0;
  prbbar: HTMLDivElement;
  innerprogress: HTMLDivElement;
  innertexts: HTMLSpanElement;
  app: App;
  constructor(ap: App) {
    this.app = ap;
    this.prbbar = document.createElement("div");
    this.prbbar.id = "progressBarrender";
    this.prbbar.innerHTML = `<div class="innerprogress" style="width:0px"></div><span class="innertexts">loading</span>`;
    document.body.appendChild(this.prbbar);
    setTimeout(() => {
      this.innerprogress = document.getElementsByClassName(
        "innerprogress"
      )[0] as HTMLDivElement;
      this.innertexts = document.getElementsByClassName(
        "innertexts"
      )[0] as HTMLSpanElement;
    }, 10);
  }

  //   渲染进度条
  renderProgress(nu: number) {
    this.innerprogress.style.width = nu * 400 + "px";
    this.innertexts.innerText =
      "Loading..." + (nu * 100).toFixed(2).toString() + "%";
    if (nu >= 1) {
      this.prbbar.style.display = "none";
      this.app.loadpage();
    }
  }
  load(): void {
    let div = document.createElement("div");
    div.style.width = "1px";
    div.style.height = "1px";
    div.style.overflow = "hidden";
    document.body.appendChild(div);
    // let length = ;
    let counts = 0;
    for (let j = 0; j < this.imglist.length; j++) {
      this.readImg(this.imglist[j]).then((res: HTMLImageElement) => {
        div.appendChild(res);
        counts++;
        console.log(counts / this.imglist.length, "当前加载个数");
        this.renderProgress(counts / this.imglist.length);
      });
    }
  }
  readImg(src: any): Promise<HTMLImageElement> {
    return new Promise((resolve, reject) => {
      var img = new Image();
      img.addEventListener("load", loadHandler);
      img.src = src.default;
      //   document.body.appendChild(img);
      img.addEventListener("error", loadError);
      function loadHandler() {
        resolve(img);
      }
      function loadError() {
        location.reload();
      }
    });
  }
}
